### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by alexmburns** [westy48/scrollphathdticker#1]
Wondering if you might be able to help, when I try to run your code it says:
Traceback (most recent call last):
  File "scrolltwitter.py", line 9, in <module>
    from twython import twython
  File "/usr/lib/python2.7/dist-packages/twython/__init__.py", line 23, in <module>
    from .api import Twython
  File "/usr/lib/python2.7/dist-packages/twython/api.py", line 14, in <module>
    from requests_oauthlib import OAuth1, OAuth2

I am pretty sure I have Twython installed, just trying to work out why it might be doing this.

Kind regards,

Alex

**Comment by westy48** [comment]
Hi Alex - I had this and forgot to document it! The Twython authentication library only installs for Python 3, so you need to force it to run in Python 3. Try "python3 yourprogram.py" 

I hope that helps - let me know how you get on. 

James

**Comment by alexmburns** [comment]
That fixed it.

Lovely bit of code, great project 👍

**Comment by westy48** [comment]
Great. I'd love to see any pics or video of your project if you'd like to share them. On Twitter I'm @jameswest - you could get them to me there if you're on it.
